# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

environment:
  global:
    USE_RTOOLS: true
    #NOT_CRAN: true
    _R_CHECK_FORCE_SUGGESTS: true
    _R_CHECK_CRAN_INCOMING_: true
    #R_CHECK_ARGS: "--run-dontrun"
  matrix:
  - R_VERSION: 3.5.0
    R_ARCH: x64
    GCC_PATH: mingw_64

  - R_VERSION: devel
    R_ARCH: x64
    GCC_PATH: mingw_64

  - R_VERSION: patched
    GCC_PATH: mingw_32

matrix:
  fast_finish: true

cache:
  - C:\RLibrary

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
