#' Tidying methods for multinomial logistic regression models
#'
#' These methods tidy the coefficients of multinomial logit regression
#' models generated by `mlogit` of the `mlogit` package.
#'
#' @param x A `mlogit` object returned from [mlogit::mlogit()].
#' @template param_confint
#' @template param_exponentiate
#' @template param_unused_dots
#' 
#' @evalRd return_tidy("y.value", regression = TRUE)
#'
#' @examples
#'
#' library(mlogit)
#' 
#' data("Fishing", package = "mlogit")
#' Fish <- mlogit.data(Fishing, varying = c(2:9), shape = "wide", choice = "mode")
#' fish.mnl <- mlogit(mode ~ price + catch, data = Fish)
#' 
#' tidy(fish.mnl)
#' tidy(fish.mnl, conf.int = 0.9)
#' glance(fish.mnl)
#' augment(fish.mnl)
#' 
#'
#' @aliases mlogit_tidiers
#' @export
#' @family mlogit tidiers
#' @seealso [tidy()], [mlogit::mlogit()]
tidy.mlogit <- function(x, conf.int = FALSE, conf.level = .95,
                          exponentiate = FALSE, ...) {
  s <- summary(x)
  ret <- as_tibble(s$CoefTable, rownames = "term")
  colnames(ret) <- c("term", "estimate", "std.error", "statistic", "p.value")
  
  if (conf.int) {
    ci <- confint(x, level = conf.level)
    ci <- as_tibble(ci, rownames = "term")
    colnames(ci) <- c("term", "conf.low", "conf.high")
    ret <- dplyr::left_join(ret, ci, by = "term")
  }
  
  if (exponentiate) 
    ret <- exponentiate(ret)
  
  ret
}

#' @templateVar class mlogit
#' @template title_desc_augment
#'
#' @template augment_NAs
#'
#' @inherit tidy.mlogit params examples
#' @template param_data
#' @template param_newdata
#' @template param_se_fit
#'
#' @evalRd return_augment(
#'   .pre = "\\item{.probability}{Logit probability.} \n \\item{.utility}{Estimated utility.}",
#'   ".fitted" )
#'
#' @export
#' @seealso [augment()],[mlogit::miscmethods.mlogit()]
#' @family mlogit tidiers
augment.mlogit <- function(x, data = model.frame(x), newdata = NULL,
                       se_fit = FALSE, ...) {
  augment_newdata(x, data, newdata, se_fit) %>%
    tidyr::separate(.rownames, into = c("id", "alternative")) %>%
    dplyr::rename(.probability = probabilities, .utility = linpred,
                  .fitted = .fitted)
  
}



#' @templateVar class mlogit
#' @template title_desc_glance
#' 
#' @inherit tidy.mlogit params examples
#' 
#' @evalRd return_glance("logLik", "AIC", "nobs", "rho2", "rho20", "statistic")
#' @export
#' @family mlogit tidiers
#' @seealso [glance()], [mlogit::mlogit()]
glance.mlogit <- function(x, ...) {
  s <- summary(x)
  nobs <- length(x$fitted.values)
  
  # likelihood ratio 
  logLik <- as.numeric(logLik(x))
  freq <- x$freq
  ll0 <- sum(freq * log(1/length(freq)))
  llC <- sum(freq * log(prop.table(freq))) 
  
  lr.stat = as.numeric(s$lratio$statistic)
  lr.p = as.numeric(s$lratio$p.value)
  
  with(
    s,
    tibble(
      logLik = as.numeric(stats::logLik(x)),
      AIC = stats::AIC(x),
      nobs = nobs,
      rho2 = 1 - logLik / llC,
      rho20 = 1 - logLik / ll0,
      lr.stat = lr.stat,
      lr.p = lr.p
    )
  )
}
